# Good example resources
# https://riggaroo.dev/using-github-actions-to-automate-our-release-process/
# https://blog.eizinger.io/12274/using-github-actions-to-automate-gitflow-style-releases

name: Auto-release

on:
  # Decide what the new version number will be
  workflow_dispatch:
    inputs:
      versionName:
        description: "One of 'major', 'minor', or 'patch'"
        required: true

jobs:
  release:
    name: Create a new release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull latest commits of main branch
        run: |
          git checkout main
          git pull

      # See https://github.com/thomaseizinger/keep-a-changelog-new-release
      - name: Update Changelog
        uses: thomaseizinger/keep-a-changelog-new-release@v1
        with:
          version: ${{ github.event.inputs.versionName }}

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install bump2version
        run: python -m pip install bumpversion  # installs bump2version

      - name: Dry run bumpversion
        run: |
          bumpversion --dry-run ${{ github.event.inputs.versionName }} --allow-dirty --verbose

      - name: Commit CHANGELOG updates
        run: |
          git config --global user.email "git@github.com"
          git config --global user.name "GitHub Bot"
          git add .
          git commit -m "Update CHANGELOG for auto-release ${{ github.event.inputs.versionName }}"

      - name: Ensure repo status is clean
        run: git status

      - name: Run bumpversion
        run: bumpversion ${{ github.event.inputs.versionName }} --verbose

      - name: Ensure tag creation
        run: git tag | grep ${{ github.event.inputs.versionName }}

      - name: Push changes with tags
        run: git push && git push --tags

      - name: Ensure complete
        run: echo "Auto-release complete!"
